[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[font]
size = 14.0

[font.normal]
family = "BitstromWera Nerd Font Mono"
style  = "Regular"

[font.bold]
family = "BitstromWera Nerd Font Mono"
style  = "Bold"

[font.italic]
family = "BitstromWera Nerd Font Mono"
style  = "Oblique"

[font.bold_italic]
family = "BitstromWera Nerd Font Mono"
style  = "Bold Oblique"
